[package]
name = "djmate"
version = "1.0.0"
description = "DJmate - Pro DJ Harmonic Suite"
authors = ["DJmate"]
edition = "2021"

[lib]
name = "djmate_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
